global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ng12-cancer-risk-assessor"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["app:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
